name : local_exp

# Traininig settings
num_epochs : 5
batch_size : 1

# evaluate 
eval_every : 3

# checkpoint
ckpt : null # TODO

# Model 
model:
    type: mag_only # mag_phase
    pooling : wavelet # maxpool
    wavelet : bior1.1 # wavelet type

# Data 
train_bs : 8 # train batch size

# Training settings
learning_rate : 0.001
lr_step_size : 50
gamma : 0.1