name : m1_haar

# Traininig settings
num_epochs : 50
batch_size : 8

# evaluate 
eval_every : 2

# checkpoint
ckpt : null # TODO

# Model 
model:
    type: mag_only # mag_phase
    pooling : wavelet # maxpool
    wavelet : haar # wavelet type

# Data 
train_bs : 8 # train batch size

# Training settings
learning_rate : 0.001
lr_step_size : 50
gamma : 0.1