name : m2_db1

# Traininig settings
num_epochs : 25
batch_size : 8

# evaluate 
eval_every : 5

# checkpoint
ckpt : null # TODO

# Model 
model:
    type: mag_phase # mag_only
    pooling : wavelet # maxpool
    wavelet : db1 # wavelet type

# Data 
train_bs : 8 # train batch size

# Training settings
learning_rate : 0.001
lr_step_size : 50
gamma : 0.1